<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Arpits-MacBook-Pro.local" ignored="0" name="Customer Create API Test" tests="12" failures="6" timestamp="2022-01-06T22:26:56 IST" time="12.555" errors="0">
  <testcase name="validCreateCustomerAPIWithInvalidSecretKey" time="2.902" classname="com.apitTestFramework.testcases.CreateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.apitTestFramework.testcases.CreateCustomerTest.validCreateCustomerAPIWithInvalidSecretKey(CreateCustomerTest.java:31)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validCreateCustomerAPIWithInvalidSecretKey -->
  <testcase name="validCreateCustomerAPIWithInvalidSecretKey" time="0.704" classname="com.apitTestFramework.testcases.CreateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.apitTestFramework.testcases.CreateCustomerTest.validCreateCustomerAPIWithInvalidSecretKey(CreateCustomerTest.java:31)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validCreateCustomerAPIWithInvalidSecretKey -->
  <testcase name="validCreateCustomerAPIWithInvalidSecretKey" time="0.697" classname="com.apitTestFramework.testcases.CreateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.apitTestFramework.testcases.CreateCustomerTest.validCreateCustomerAPIWithInvalidSecretKey(CreateCustomerTest.java:31)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validCreateCustomerAPIWithInvalidSecretKey -->
  <testcase name="validCreateCustomerAPIWithInvalidSecretKey" time="0.682" classname="com.apitTestFramework.testcases.CreateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.apitTestFramework.testcases.CreateCustomerTest.validCreateCustomerAPIWithInvalidSecretKey(CreateCustomerTest.java:31)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validCreateCustomerAPIWithInvalidSecretKey -->
  <testcase name="validCreateCustomerAPIWithInvalidSecretKey" time="0.708" classname="com.apitTestFramework.testcases.CreateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.apitTestFramework.testcases.CreateCustomerTest.validCreateCustomerAPIWithInvalidSecretKey(CreateCustomerTest.java:31)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validCreateCustomerAPIWithInvalidSecretKey -->
  <testcase name="validCreateCustomerAPIWithInvalidSecretKey" time="0.705" classname="com.apitTestFramework.testcases.CreateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.apitTestFramework.testcases.CreateCustomerTest.validCreateCustomerAPIWithInvalidSecretKey(CreateCustomerTest.java:31)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validCreateCustomerAPIWithInvalidSecretKey -->
  <testcase name="validCreateCustomerAPIWithValidSecretKey" time="1.044" classname="com.apitTestFramework.testcases.CreateCustomerTest"/>
  <testcase name="validCreateCustomerAPIWithValidSecretKey" time="1.219" classname="com.apitTestFramework.testcases.CreateCustomerTest"/>
  <testcase name="validCreateCustomerAPIWithValidSecretKey" time="0.909" classname="com.apitTestFramework.testcases.CreateCustomerTest"/>
  <testcase name="validCreateCustomerAPIWithValidSecretKey" time="0.963" classname="com.apitTestFramework.testcases.CreateCustomerTest"/>
  <testcase name="validCreateCustomerAPIWithValidSecretKey" time="0.992" classname="com.apitTestFramework.testcases.CreateCustomerTest"/>
  <testcase name="validCreateCustomerAPIWithValidSecretKey" time="0.936" classname="com.apitTestFramework.testcases.CreateCustomerTest"/>
</testsuite> <!-- Customer Create API Test -->
