<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" ignored="0" total="12" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="All Test Suite" duration-ms="12555" started-at="2022-01-06T22:26:44 IST" finished-at="2022-01-06T22:26:56 IST">
    <groups>
    </groups>
    <test name="Customer Create API Test" duration-ms="12555" started-at="2022-01-06T22:26:44 IST" finished-at="2022-01-06T22:26:56 IST">
      <class name="com.apitTestFramework.testcases.CreateCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.apitTestFramework.testcases.CreateCustomerTest@6e950bcf]" name="setUp" is-config="true" duration-ms="491" started-at="2022-01-06T22:26:43 IST" finished-at="2022-01-06T22:26:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validCreateCustomerAPIWithInvalidSecretKey(java.util.Hashtable)[pri:0, instance:com.apitTestFramework.testcases.CreateCustomerTest@6e950bcf]" name="validCreateCustomerAPIWithInvalidSecretKey" duration-ms="2902" started-at="2022-01-06T22:26:44 IST" data-provider="getData" finished-at="2022-01-06T22:26:47 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=qsvm26@gmail.com, name=Hisako Weber II, description=j73ss996b6}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.apitTestFramework.testcases.CreateCustomerTest.validCreateCustomerAPIWithInvalidSecretKey(CreateCustomerTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCreateCustomerAPIWithInvalidSecretKey -->
        <test-method status="FAIL" signature="validCreateCustomerAPIWithInvalidSecretKey(java.util.Hashtable)[pri:0, instance:com.apitTestFramework.testcases.CreateCustomerTest@6e950bcf]" name="validCreateCustomerAPIWithInvalidSecretKey" duration-ms="704" started-at="2022-01-06T22:26:47 IST" data-provider="getData" finished-at="2022-01-06T22:26:48 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=nyhw95@gmail.com, name=Julian Nienow PhD, description=dtayl77hb7}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.apitTestFramework.testcases.CreateCustomerTest.validCreateCustomerAPIWithInvalidSecretKey(CreateCustomerTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCreateCustomerAPIWithInvalidSecretKey -->
        <test-method status="FAIL" signature="validCreateCustomerAPIWithInvalidSecretKey(java.util.Hashtable)[pri:0, instance:com.apitTestFramework.testcases.CreateCustomerTest@6e950bcf]" name="validCreateCustomerAPIWithInvalidSecretKey" duration-ms="697" started-at="2022-01-06T22:26:48 IST" data-provider="getData" finished-at="2022-01-06T22:26:48 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=uxwp08@gmail.com, name=Riva Wilderman, description=466uza5s8r}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.apitTestFramework.testcases.CreateCustomerTest.validCreateCustomerAPIWithInvalidSecretKey(CreateCustomerTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCreateCustomerAPIWithInvalidSecretKey -->
        <test-method status="FAIL" signature="validCreateCustomerAPIWithInvalidSecretKey(java.util.Hashtable)[pri:0, instance:com.apitTestFramework.testcases.CreateCustomerTest@6e950bcf]" name="validCreateCustomerAPIWithInvalidSecretKey" duration-ms="682" started-at="2022-01-06T22:26:48 IST" data-provider="getData" finished-at="2022-01-06T22:26:49 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=qtvf61@gmail.com, name=Alice Tremblay, description=djz5us81js}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.apitTestFramework.testcases.CreateCustomerTest.validCreateCustomerAPIWithInvalidSecretKey(CreateCustomerTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCreateCustomerAPIWithInvalidSecretKey -->
        <test-method status="FAIL" signature="validCreateCustomerAPIWithInvalidSecretKey(java.util.Hashtable)[pri:0, instance:com.apitTestFramework.testcases.CreateCustomerTest@6e950bcf]" name="validCreateCustomerAPIWithInvalidSecretKey" duration-ms="708" started-at="2022-01-06T22:26:49 IST" data-provider="getData" finished-at="2022-01-06T22:26:50 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=iruc99@gmail.com, name=Bunny Schoen DDS, description=6gww3l915t}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.apitTestFramework.testcases.CreateCustomerTest.validCreateCustomerAPIWithInvalidSecretKey(CreateCustomerTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCreateCustomerAPIWithInvalidSecretKey -->
        <test-method status="FAIL" signature="validCreateCustomerAPIWithInvalidSecretKey(java.util.Hashtable)[pri:0, instance:com.apitTestFramework.testcases.CreateCustomerTest@6e950bcf]" name="validCreateCustomerAPIWithInvalidSecretKey" duration-ms="705" started-at="2022-01-06T22:26:50 IST" data-provider="getData" finished-at="2022-01-06T22:26:50 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=wynz08@gmail.com, name=Dr. Tim Jakubowski, description=3xha33c175}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.apitTestFramework.testcases.CreateCustomerTest.validCreateCustomerAPIWithInvalidSecretKey(CreateCustomerTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCreateCustomerAPIWithInvalidSecretKey -->
        <test-method status="PASS" signature="validCreateCustomerAPIWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.apitTestFramework.testcases.CreateCustomerTest@6e950bcf]" name="validCreateCustomerAPIWithValidSecretKey" duration-ms="1044" started-at="2022-01-06T22:26:50 IST" data-provider="getData" finished-at="2022-01-06T22:26:51 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=hung.rutherford@yahoo.com, name=Sydney Quigley, description=Earum enim et maxime reprehenderit maxime.}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCreateCustomerAPIWithValidSecretKey -->
        <test-method status="PASS" signature="validCreateCustomerAPIWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.apitTestFramework.testcases.CreateCustomerTest@6e950bcf]" name="validCreateCustomerAPIWithValidSecretKey" duration-ms="1219" started-at="2022-01-06T22:26:51 IST" data-provider="getData" finished-at="2022-01-06T22:26:53 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=precious.pollich@hotmail.com, name=Guillermo Tremblay, description=Incidunt aut laboriosam amet aspernatur.}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCreateCustomerAPIWithValidSecretKey -->
        <test-method status="PASS" signature="validCreateCustomerAPIWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.apitTestFramework.testcases.CreateCustomerTest@6e950bcf]" name="validCreateCustomerAPIWithValidSecretKey" duration-ms="909" started-at="2022-01-06T22:26:53 IST" data-provider="getData" finished-at="2022-01-06T22:26:54 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=roma.hoeger@gmail.com, name=Sarita Runte, description=Consequuntur corporis labore.}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCreateCustomerAPIWithValidSecretKey -->
        <test-method status="PASS" signature="validCreateCustomerAPIWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.apitTestFramework.testcases.CreateCustomerTest@6e950bcf]" name="validCreateCustomerAPIWithValidSecretKey" duration-ms="963" started-at="2022-01-06T22:26:54 IST" data-provider="getData" finished-at="2022-01-06T22:26:54 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=priscila.heidenreich@hotmail.com, name=Thanh Heller, description=Incidunt eos voluptatem.}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCreateCustomerAPIWithValidSecretKey -->
        <test-method status="PASS" signature="validCreateCustomerAPIWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.apitTestFramework.testcases.CreateCustomerTest@6e950bcf]" name="validCreateCustomerAPIWithValidSecretKey" duration-ms="992" started-at="2022-01-06T22:26:54 IST" data-provider="getData" finished-at="2022-01-06T22:26:55 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=cathi.gusikowski@hotmail.com, name=Miss Rudolph Walsh, description=Quam atque vel excepturi nam illo.}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCreateCustomerAPIWithValidSecretKey -->
        <test-method status="PASS" signature="validCreateCustomerAPIWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.apitTestFramework.testcases.CreateCustomerTest@6e950bcf]" name="validCreateCustomerAPIWithValidSecretKey" duration-ms="936" started-at="2022-01-06T22:26:55 IST" data-provider="getData" finished-at="2022-01-06T22:26:56 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=liz.kuhn@gmail.com, name=Mrs. Sabina Nader, description=Praesentium sed modi culpa.}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCreateCustomerAPIWithValidSecretKey -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.apitTestFramework.testcases.CreateCustomerTest@6e950bcf]" name="tearDown" is-config="true" duration-ms="1" started-at="2022-01-06T22:26:57 IST" finished-at="2022-01-06T22:26:57 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.apitTestFramework.testcases.CreateCustomerTest -->
    </test> <!-- Customer Create API Test -->
  </suite> <!-- All Test Suite -->
</testng-results>
